"use client";
import { useEffect, useState } from "react";
import { useParams, useRouter } from "next/navigation";
import AppIcon from "../common/icon/AppIcon";
import { jobPostingApi, type PublicJobPosting } from "../../services/api";

export default function AnnouncementDetail() {
  const router = useRouter(); const { id } = useParams<{ id: string }>(); const [notice, setNotice] = useState<PublicJobPosting | null>(null);
  useEffect(() => { jobPostingApi.get(id).then(({ data }) => setNotice(data)); }, [id]);
  if (!notice) return <main className="min-h-screen bg-[#1f1f1f] sm:flex sm:justify-center sm:px-4 sm:py-8"><section className="min-h-screen w-full max-w-[402px] bg-[#f2fcff] p-8 text-center text-sm text-[#777]">공고를 불러오는 중입니다.</section></main>;
  const Detail = ({ label, children }: { label: string; children: React.ReactNode }) => <div className="mt-4"><h3 className="text-[12px] font-medium">{label}</h3><p className="mt-1 text-[12px] leading-5 text-[#424242]">{children}</p></div>;
  return <main className="min-h-screen bg-[#1f1f1f] sm:flex sm:justify-center sm:px-4 sm:py-8"><section className="min-h-screen w-full max-w-[402px] overflow-hidden bg-[#f2fcff] text-[#1b1e20]" style={{fontFamily:"Pretendard, Inter, sans-serif"}}><header className="relative h-[115px] bg-[#e9ece1]"><button onClick={() => router.back()} aria-label="뒤로가기" className="absolute left-8 top-[73px] bg-transparent p-0"><AppIcon name="chevron-left" size={24}/></button><h1 className="pt-[76px] text-center text-[18px]">공고 상세사항</h1></header><div className="px-[25px] pt-[24px]"><article className="rounded-[12px] bg-white px-[20px] py-[26px] shadow-[inset_0_3px_12.9px_rgba(124,129,118,0.25)]"><h2 className="text-[22px] font-normal leading-7">{notice.title}</h2><Detail label="작업일시">{notice.workDate}　{notice.startTime.slice(0,5)} ~ {notice.endTime.slice(0,5)}</Detail><Detail label="집결 장소">{notice.cityCounty}　{notice.meetingPlace}</Detail><Detail label="모집인원">{notice.capacity}</Detail><Detail label="준비물">개인 물병, 모자</Detail><Detail label="작업 내용">{notice.description || `${notice.crop} ${notice.workType} 작업입니다.`}</Detail></article><section className="mt-[35px] rounded-[12px] bg-[rgba(238,238,238,0.55)] px-[20px] py-[16px]"><h3 className="text-[12px]">안전 주의 사항</h3><p className="mt-3 text-[12px] leading-5 text-[#424242]">무리한 작업은 되도록 피해주세요. 또한 날씨에 따라 일정이 변경될 수 있으니 이 점 참고 바랍니다.</p></section><p className="mt-[18px] text-center text-[10px] leading-4 text-[#5c5c5c]">위 내용은 입력하신 정보를 바탕으로 ai가 생성한 공고문입니다. 내용을 확인<br/>후에 클릭해서 수정한뒤 발송 신청 바랍니다.</p><section className="mt-[18px] rounded-[12px] border border-[#a4a6a3] px-[20px] py-[16px]"><div className="flex items-center gap-2 text-[15px] text-[#5c5c5c]"><AppIcon name="search" size={24}/>공식 확인 안내</div><p className="mt-3 text-[10px] leading-4 text-[#5c5c5c]">ai가 생성한 내용은 참고용이며, 실제 현장 안내가 우선합니다.<br/>작업 장소와 집결시간 등 주요 정보는 중개 센터를 검토 후 최종 확정됩니다.</p></section></div></section></main>;
}
